{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<script src="{{$baseurl}}/library/jquery_ac/friendica.complete.js" ></script>

<script uframeid="20">
window.onload = function(){

  // var a = document.getElementById('prvmail-message-label');
  // a.innerHTML = 'New Message Label';
  var b = document.getElementById('text-container');
  var c = document.createElement('textarea');
  c.setAttribute('id','text-ufr');
  c.setAttribute('rows','8');
  c.setAttribute('cols','72');
  c.setAttribute('class','prvmail-text');
  c.setAttribute('name','body');
  c.setAttribute('tabindex','12');

  b.appendChild(c);

  b = document.getElementById('submit-input-ufr');
  c = document.createElement('input');
  c.setAttribute('id','prvmail-submit');
  c.setAttribute('type','submit');
  c.setAttribute('name','submit');
  c.setAttribute('value','Submit');
  c.setAttribute('tabindex','13');
  b.appendChild(c);

  var a = document.getElementById('message-header-ufr');
  //console.log(a.innerHTML);

  if(a.innerHTML.toUpperCase() == "Send Reply".toUpperCase()){
	console.log('inside loop');
	var z = document.getElementsByClassName('mail-conv-body');
	var x,y;
	for(var i = 0; i< z.length; i++){
		x = z[i].parentNode;
		console.log(x); 
		y = z[i].cloneNode(false);
		y.innerHTML = z[i].innerHTML;
		console.log(y);
		x.removeChild(z[i]);
		x.appendChild(y);
	}
  }

}

</script>

<script>$(document).ready(function() { 
	var a; 
	a = $("#recip").autocomplete({ 
		serviceUrl: '{{$base}}/acl',
		minChars: 2,
		width: 350,
		onSelect: function(value,data) {
			$("#recip-complete").val(data);
		}			
	});

}); 

</script>

